"""Default values and unit conversion factors of the network extension."""

# Default values of the link parameters
DEFAULT_BANDWIDTH_MBPS = 100.0
"""Default link bandwidth in Mbps."""

DEFAULT_LENGTH_KM = 1.0
"""Default physical link length in kilometers."""

DEFAULT_PROPAGATION_SPEED_KM_S = 200000.0
"""Default signal propagation speed through the medium (e.g., fiber) in km/s."""

# Fallbacks for links without physical attributes
MIN_LENGTH_KM = 0.0
"""Physical length, in km, assumed for a link without the ``length_km`` attribute."""

MIN_PROPAGATION_SPEED = 0.001
"""Propagation speed, in km/s, assumed for a link without the
``propagation_speed_km_s`` attribute. It is positive, to avoid divisions by zero.
"""

# Unit conversion factors
MBPS_TO_BPS = 1_000_000.0
"""Multiplier to convert megabits per second to bits per second."""

SEC_TO_MS = 1000.0
"""Multiplier to convert seconds to milliseconds."""

BYTES_TO_BITS = 8
"""Multiplier to convert bytes to bits."""


# Default values of the traffic flows
DEFAULT_AVG_PACKETS_PER_STEP = 1.0
"""Default average number of packets generated by a flow at each step."""

DEFAULT_PACKET_SIZE_BYTES = 1500
"""Default packet size of a flow, in bytes."""

__all__ = [
    "BYTES_TO_BITS",
    "DEFAULT_AVG_PACKETS_PER_STEP",
    "DEFAULT_BANDWIDTH_MBPS",
    "DEFAULT_LENGTH_KM",
    "DEFAULT_PACKET_SIZE_BYTES",
    "DEFAULT_PROPAGATION_SPEED_KM_S",
    "MBPS_TO_BPS",
    "MIN_LENGTH_KM",
    "MIN_PROPAGATION_SPEED",
    "SEC_TO_MS",
]
