"""Application model with stochastic traffic generation for the ECLYPSE framework.

This module defines :class:`NetworkApplication`, an ECLYPSE
:class:`~eclypse.graph.Application` whose edges are traffic flows between services.
At every step, each flow generates a Poisson-distributed number of packets.
"""

import numpy as np

from eclypse.graph import Application

from .constants import (
    DEFAULT_AVG_PACKETS_PER_STEP,
    DEFAULT_PACKET_SIZE_BYTES,
)


class GeneratedTraffic:
    """Packets generated by an application in one step.

    Packets are stored as arrays with one entry per packet, in generation order:
    packets are grouped by flow, following the order of the flows in ``flows``.

    Attributes:
        flows (list[tuple[str, str, int]]): The source service, destination service
            and packet size in bytes of every flow of the application.
        flow (np.ndarray): The position in ``flows`` of the flow of each packet.
        id (np.ndarray): The unique identifier of each packet.
        step (int): The simulation step in which the packets were generated.
    """

    __slots__ = ("flow", "flows", "id", "step")

    def __init__(self, flows, flow: np.ndarray, ids: np.ndarray, step: int):
        """Initialize the traffic generated in a step.

        Args:
            flows (list[tuple[str, str, int]]): The flows of the application.
            flow (np.ndarray): The flow of each packet.
            ids (np.ndarray): The identifier of each packet.
            step (int): The simulation step of the generation.
        """
        self.flows = flows
        self.flow = flow
        self.id = ids
        self.step = step

    def __len__(self) -> int:
        """Return the number of generated packets."""
        return len(self.id)


class NetworkApplication(Application):
    """ECLYPSE application whose edges are stochastic traffic flows.

    Each edge ``u -> v`` defines a flow from service ``u`` to service ``v``,
    characterized by a packet size and an average number of packets per step. At
    every step, the number of packets of each flow is drawn from a Poisson
    distribution with that average.

    Attributes:
        current_step (int): The current simulation step, advanced by the
            :class:`~eclypse.network.PacketGenerationEvent`.
        generated (GeneratedTraffic | None): The packets generated in the current
            step and not yet injected into the network, or None if there are none.
        _packet_counter (int): Number of packets generated so far, used to assign
            unique packet identifiers.
    """

    def __init__(self, *args, **kwargs):
        """Initialize an application without traffic.

        Args:
            *args: Positional arguments passed to
                :class:`~eclypse.graph.Application`.
            **kwargs: Keyword arguments passed to
                :class:`~eclypse.graph.Application`.
        """
        super().__init__(*args, **kwargs)
        self._packet_counter = 0
        self.current_step = 0
        self.generated: GeneratedTraffic | None = None

    @property
    def num_generated(self) -> int:
        """Number of packets generated in the current step and not yet injected."""
        return 0 if self.generated is None else len(self.generated)

    def add_edge(
        self,
        u_of_edge: str,
        v_of_edge: str,
        symmetric: bool = False,
        strict: bool = True,
        packet_size_bytes: int = DEFAULT_PACKET_SIZE_BYTES,
        avg_packets_per_step: float = DEFAULT_AVG_PACKETS_PER_STEP,
        **attr,
    ):
        """Add a traffic flow between two services.

        Args:
            u_of_edge (str): The source service of the flow.
            v_of_edge (str): The destination service of the flow.
            symmetric (bool): If True, also add the flow in the opposite direction.
                Defaults to False.
            strict (bool): If True, raise an error if the edge assets are
                inconsistent; otherwise log a warning. Defaults to True.
            packet_size_bytes (int): The size of the packets of the flow, in bytes.
                Defaults to
                :data:`~eclypse.network.constants.DEFAULT_PACKET_SIZE_BYTES`.
            avg_packets_per_step (float): The average number of packets generated per
                step (the Poisson rate). Defaults to
                :data:`~eclypse.network.constants.DEFAULT_AVG_PACKETS_PER_STEP`.
            **attr: Additional attributes of the edge.

        Raises:
            ValueError: If ``packet_size_bytes`` is not positive or
                ``avg_packets_per_step`` is negative.
        """
        if packet_size_bytes <= 0:
            raise ValueError(f"Packet size must be > 0. Found: {packet_size_bytes}")
        if avg_packets_per_step < 0:
            raise ValueError(f"Packet rate must be >= 0. Found: {avg_packets_per_step}")
        attr["packet_size_bytes"] = packet_size_bytes
        attr["avg_packets_per_step"] = avg_packets_per_step
        super().add_edge(
            u_of_edge, v_of_edge, symmetric=symmetric, strict=strict, **attr
        )

        self.logger.info(
            f"Added flow {u_of_edge}->{v_of_edge}, "
            f"{avg_packets_per_step} pkt/step (avg), "
            f"size {packet_size_bytes}B"
        )

    def generate_traffic_for_step(self, step: int) -> None:
        """Generate the packets of all the flows for a simulation step.

        The number of packets of each flow is drawn from a Poisson distribution
        whose rate is the ``avg_packets_per_step`` attribute of the flow. Flow
        parameters are read at every call, so changes made by update policies take
        effect immediately. The result is stored in :attr:`generated`, replacing
        any packets not yet injected.

        Args:
            step (int): The simulation step in which the packets are generated.
        """
        self.generated = None

        # Flow parameters are read live (update policies may change them)
        flows = []
        rates = []
        for u, nbrs in self._adj.items():
            for v, data in nbrs.items():
                flows.append(
                    (u, v, data.get("packet_size_bytes", DEFAULT_PACKET_SIZE_BYTES))
                )
                rates.append(
                    data.get("avg_packets_per_step", DEFAULT_AVG_PACKETS_PER_STEP)
                )
        if not flows:
            return

        # One Poisson draw per flow, taken from the global numpy random state so
        # that results are reproducible with np.random.seed
        counts = np.random.poisson(rates)
        total = int(counts.sum())

        # Packets are numbered consecutively, flow after flow
        ids = np.arange(
            self._packet_counter + 1, self._packet_counter + 1 + total, dtype=np.int64
        )
        self._packet_counter += total
        self.generated = GeneratedTraffic(
            flows, np.repeat(np.arange(len(flows)), counts), ids, step
        )
