"""Module containing the traffic routing execution event for the ECLYPSE framework."""

import random
from itertools import accumulate

import numpy as np

from eclypse.workflow.event import EclypseEvent
from eclypse.workflow.trigger import CascadeTrigger

from .constants import DEFAULT_BANDWIDTH_MBPS
from .network import (
    Network,
    PacketBatch,
)
from .network_application import NetworkApplication


class RoutingEvent(EclypseEvent):
    """Worker event that executes routing logic and updates application state.

    This event is called exactly once per step by the simulation engine. It
    injects the packets generated in the step on their source hosts, orders the
    packets waiting on every router with the probabilistic multiplexer, and
    forwards all of them by one hop with a single batched call.

    Processing order (hosts in ``infra.hosts`` order, then routers in
    ``infra.routers`` order, each router multiplexing its input links) is the same
    as a packet-by-packet loop, and so are the results.
    """

    def __init__(self, step_duration_s=0.001):
        """Initialize the traffic routing execution event.

        Args:
            step_duration_s (float): The duration of a single simulation step
                in seconds. Defaults to 0.001.
        """
        self.step_duration_s = step_duration_s
        super().__init__(
            name="traffic_routing_execution",
            event_type="application",
            triggers=[CascadeTrigger("step")],
        )

    def _inject_generated_packets(
        self, app: NetworkApplication, placement, infra: Network
    ) -> PacketBatch:
        """Turn the packets generated by the application into a PacketBatch.

        Resolves the source and destination node of every flow with the placement,
        discards the packets of unmapped services or whose source is a Router, and
        orders the packets by source host (in ``infra.hosts`` order), keeping the
        generation order within a host.

        Args:
            app (NetworkApplication): The application layer containing generated \
            packets.
            placement: The placement strategy to resolve service to node mapping.
            infra (Network): The network infrastructure.

        Returns:
            PacketBatch: The injected packets, in host processing order.
        """
        generated = app.generated
        app.generated = None
        if generated is None or not len(generated):
            return PacketBatch.empty()

        flows = generated.flows
        node_ids = infra._node_ids  # pylint: disable=protected-access
        host_rank = infra._host_rank  # pylint: disable=protected-access
        router_rank = infra._router_rank  # pylint: disable=protected-access

        placement_cache: dict[str, int] = {}

        def resolve(service: str) -> int:
            if service not in placement_cache:
                try:
                    node = placement.service_placement(service_id=service)
                    idx = node_ids.get(node, -1)
                except KeyError as e:
                    infra.logger.debug(f"Packet dropped locally: Unmapped service {e}")
                    idx = -1
                placement_cache[service] = idx
            return placement_cache[service]

        n_flows = len(flows)
        flow_src = np.full(n_flows, -1, dtype=np.int64)
        flow_dst = np.full(n_flows, -1, dtype=np.int64)
        per_flow = np.bincount(generated.flow, minlength=n_flows)
        for f in np.flatnonzero(per_flow).tolist():
            src_service, dst_service, _ = flows[f]
            src, dst = resolve(src_service), resolve(dst_service)
            if src < 0 or dst < 0:
                continue
            if router_rank[src] >= 0:
                infra.logger.warning(
                    f"{per_flow[f]} packets dropped: the service '{src_service}' is "
                    f"located on node '{infra.node_name(src)}' which is configured as "
                    f"a Router. Only Host nodes can generate traffic!"
                )
                continue
            if host_rank[src] < 0:
                continue
            flow_src[f] = src
            flow_dst[f] = dst

        flow = generated.flow
        src = flow_src[flow]
        keep = (src >= 0) & (flow_dst[flow] >= 0)
        flow, src, ids = flow[keep], src[keep], generated.id[keep]
        order = np.argsort(host_rank[src], kind="stable")
        flow, src, ids = flow[order], src[order], ids[order]

        sizes = np.array([f[2] for f in flows], dtype=np.int64)
        n = len(ids)
        return PacketBatch(
            id=ids,
            src=src,
            dst=flow_dst[flow],
            size=sizes[flow],
            step=np.full(n, generated.step, dtype=np.int64),
            cur=src,
            prev=np.full(n, -1, dtype=np.int64),
            hop=np.zeros(n, dtype=np.int64),
        )

    def _input_bandwidths(
        self, router: str, prev_nodes: list[int], infra: Network
    ) -> list[float]:
        """Return the bandwidth (Mbps) of the link from each previous node."""
        adj = infra._adj  # pylint: disable=protected-access
        return [
            adj.get(infra.node_name(p), {})
            .get(router, {})
            .get("bandwidth_mbps", DEFAULT_BANDWIDTH_MBPS)
            for p in prev_nodes
        ]

    def _build_probabilistic_queue(
        self, router: str, packets: PacketBatch, infra: Network
    ) -> PacketBatch:
        """Merge the input queues of a router probabilistically based on bandwidth.

        Implements a probabilistic multiplexer: packets are extracted from the
        active input queues (one per previous node) by tossing a 'weighted coin'
        based on the bandwidth of the input links, simulating hardware
        fair-queuing based on link capacity.

        Each toss is exactly ``random.choices(sources, weights, k=1)`` (cumulative
        weights + bisect on ``random() * total``), so the random stream and the
        resulting order are the same as one call per packet. The tosses are made in
        epochs: an epoch of ``d = min(remaining packets)`` tosses cannot empty a
        queue before its last toss, so the weights are constant within it and all
        its tosses are resolved with one ``searchsorted``.

        Args:
            router (str): The router whose buffer is multiplexed.
            packets (PacketBatch): The packets in the buffer, in arrival order.
            infra (Network): The network infrastructure.

        Returns:
            PacketBatch: The packets in processing order.
        """
        rnd = random.random
        n = len(packets)
        uniq, first, inverse = np.unique(
            packets.prev, return_index=True, return_inverse=True
        )
        k = len(uniq)
        if k == 1:
            # One input: the order is fixed, but one toss per packet is consumed
            for _ in range(n):
                rnd()
            return packets

        # Sources in order of first appearance (as the input queues were created)
        appearance = np.argsort(first)
        rank = np.empty(k, dtype=np.int64)
        rank[appearance] = np.arange(k)
        source_of = rank[inverse.reshape(-1)]
        weights = self._input_bandwidths(router, uniq[appearance].tolist(), infra)
        remaining = np.bincount(source_of, minlength=k).tolist()

        active = list(range(k))
        sequence = []
        while active:
            if len(active) == 1:
                left = remaining[active[0]]
                for _ in range(left):
                    rnd()
                sequence.append(np.full(left, active[0], dtype=np.int64))
                break
            cum_weights = list(accumulate([weights[j] for j in active]))
            total = cum_weights[-1] + 0.0
            bounds = np.array(cum_weights[:-1])
            active_arr = np.array(active, dtype=np.int64)
            while True:
                d = min(remaining[j] for j in active)
                draws = np.array([rnd() for _ in range(d)])
                picks = np.searchsorted(bounds, draws * total, side="right")
                sequence.append(active_arr[picks])
                got = np.bincount(picks, minlength=len(active)).tolist()
                emptied = -1
                for pos, j in enumerate(active):
                    remaining[j] -= got[pos]
                    if remaining[j] == 0:
                        emptied = pos
                if emptied >= 0:
                    active.pop(emptied)
                    break

        # The i-th toss of source j takes the i-th packet of source j
        seq = np.concatenate(sequence)
        order = np.empty(n, dtype=np.int64)
        order[np.argsort(seq, kind="stable")] = np.argsort(source_of, kind="stable")
        return packets.take(order)

    def __call__(self, app: NetworkApplication, placement, infra: Network, **_kwargs):
        """Execute the routing logic for the current step.

        Args:
            app (NetworkApplication): The application layer with generated \
            packets and step info.
            placement: The placement strategy manager.
            infra (Network): The network infrastructure.
            **kwargs: Additional keyword arguments.
        """
        infra.clear_step_telemetry()
        infra._ensure_tables()  # pylint: disable=protected-access
        current_time_s = app.current_step * self.step_duration_s

        # Hosts: the packets generated in this step
        batches = [self._inject_generated_packets(app, placement, infra)]

        # Routers: the packets that arrived in the previous step
        logger = infra.logger.opt(lazy=True)
        for router, packets in infra.take_router_batches():
            ordered = self._build_probabilistic_queue(router, packets, infra)
            if len(ordered) > 1:
                # Lazy: the string is built only if the INFO level is enabled
                logger.info(  # noqa: PLE1205 (loguru {} formatting)
                    "{} order: [{}]",
                    lambda router=router: router,
                    lambda p=ordered: ", ".join(
                        f"{i} ({infra.node_name(prev)})"
                        for i, prev in zip(p.id.tolist(), p.prev.tolist(), strict=True)
                    ),
                )
            batches.append(ordered)

        # Forward everything by one hop, in processing order
        infra.forward_batch(PacketBatch.concat(batches), current_time_s)

        # Update the link latencies based on the telemetry of the current step
        infra.update_link_latencies()
